EstateMaximumMVC/Controllers/ApartmentController.cs
using EstateMaximum.Models.Apartments;
using EstateMaximum.Models.Houses;
using EstateMaximum.Services.Apartments;
using EstateMaximum.Services.Houses;
using EstateMaximum.Services.IServices;
using Microsoft.AspNetCore.Mvc;

namespace EstateMaximumMVC.Controllers
{
    public class ApartmentController : Controller
    {
        private readonly IApartmentServices _apartmentServices;

        public ApartmentController(IApartmentServices apartmentServices)
        {
            _apartmentServices = apartmentServices;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var apartments = await _apartmentServices.ApartmentListItemAsync();
            return View(apartments);
        }


        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            var apartment = await _apartmentServices.GetApartmentAsync(id);
            if (apartment == null) return BadRequest();
            return View(apartment);
        }
        

        [HttpGet]
        public async Task<IActionResult> Create()
        { 

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(ApartmentCreate model)
        {
            if (!ModelState.IsValid) return View(ModelState);

            if (await _apartmentServices.AddApartmentAsync(model))
                return RedirectToAction(nameof(Index));

            return View(model);
        } 
        

        
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ApartmentEdit model)
        {
            if (!ModelState.IsValid) return View(ModelState);

            if (await _apartmentServices.EditApartmentAsync(model))
                return RedirectToAction(nameof(Index));

            return View(model);
        } 


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var apartment = await _apartmentServices.GetApartmentAsync(id);
            if (apartment == null) return BadRequest();
            var apartmentEdit = new ApartmentEdit
            {
                ApartmentId = apartment.ApartmentId,
                ApartmentNumber = apartment.ApartmentNumber,
                ApartmentName = apartment.ApartmentName,
                Price = apartment.Price,    
                Address = apartment.Address,
                Bathrooms   = apartment.Bathrooms,
                Bedrooms = apartment.Bedrooms,
                City = apartment.City,
                Description = apartment.Description,
                Gym = apartment.Gym,
                Pool = apartment.Pool,
                Size = apartment.Size,
            };
            return View(apartmentEdit);
        }
        
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var apartment = await _apartmentServices.GetApartmentAsync(id);
            return View(apartment);

        }      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id)
        {
            var apartment = await _apartmentServices.DeleteApartmentAsync(id.Value);
            if (apartment == false) return BadRequest();
            return View();
        }


    }
}

EstateMaximumMVC/Controllers/HousesController.cs
using EstateMaximum.Models.Apartments;
using EstateMaximum.Models.Houses;
using EstateMaximum.Services.Apartments;
using EstateMaximum.Services.IServices;
using Microsoft.AspNetCore.Mvc;

namespace EstateMaximumMVC.Controllers
{
    public class HousesController : Controller
    {
        private IHouseServices _houseServices;
        

        public HousesController(IHouseServices houseServices)
        {
            _houseServices = houseServices;
            
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var houses = await _houseServices.HouseListItemsAsync();
            return View(houses);
        }


        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            var house = await _houseServices.DetailHouseAsync(id);
        
            return View(house);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(HouseCreate model)
        {
            if (!ModelState.IsValid) return View(ModelState);

            if (await _houseServices.AddHouseAsync(model))
                return RedirectToAction(nameof(Index));

            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult>Edit(int id)
        {
            var house = await _houseServices.DetailHouseAsync(id);
            if (house == null) return BadRequest();
            var houseEdit = new HouseEdit
            { 
                Id = house.Id,
                Address = house.Address,
                Bedrooms    = house.Bedrooms,
                HouseNumber = house.HouseNumber,
                City = house.City,
                Description= house.Description,
                Price= house.Price,
                Size= house.Size,
                Stories= house.Stories
            };

            return View(houseEdit);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(HouseEdit model)
        {
            var house = await _houseServices.EditHouseAsync(model);
            if (house == false) return BadRequest();
            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            var house = await _houseServices.DetailHouseAsync(id.Value);
           
            return View(house);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Delete(int id)
        {
            var house = await _houseServices.DeleteHouseAsync(id);
            if (house == false) return BadRequest();


            return RedirectToAction("Index");
        }
    }
}

EstateMaximumMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EstateMaximumMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EstateMaximumMVC.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Bodoni:ital,wght@0,400..700;1,400..700&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Estate Maximum!</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    @*     <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Apartment" asp-action="Index">Apartments</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Houses" asp-action="Index">Houses</a>
                        </li> 
                    *@
                        <li class="nav-link breadcrumb-item"><a asp-controller="Apartment" asp-action="Index">Apartments</a></li>
                        <li class="nav-link breadcrumb-item"><a asp-controller="Houses" asp-action="Index">Houses</a></li>
                    </ul>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">

                            @* <li class="breadcrumb-item active" aria-current="page"></li> *@
                        </ol>
                    </nav>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EstateMaximumMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy"> Privacy </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>